cmdline/cmdline.c, src/mrmailbox.c, src/mrsmtp.c, src/mrstock.c
The only **fix** is:  swap arguments for the _addcontact_ command in cmdline.
The rest is just cosmetics :)
=> The "minor changes" PR

src/mrchat.c, src/mrchat.h, src/mrcontact-private.h, src/mrevent.h
Did not know the meaning, thus how to correct the following:
https://github.com/deltachat/deltachat-core/blob/f14c518b70995dcbdf49f86db5208d93f1b1cb6c/src/mrevent.h#L270
=> Grammar changes

src/mrimap.c, src/mrmailbox.c, src/mrtools.c
Log text improvements and typo corrections in comments.
Corrected log text about message deletion in mrimap.c.
=> Log text and typo corrections

src/mrimap.c, src/mrmailbox.c
Reference (***) is between two files mrimap.c <-> mrmailbox.c
=> complemented reference

cmdline/cmdline.c, src/mrmailbox-private.h, src/mrmailbox.c
1) minor changes around reset_tables
2) new function to cleanup contacts
=> cmdline functions

src/mrimap.c
select_folder__() should be independent from other stuff to simplidy uidvalidity comparison in the future
=> remove folder selection from adding flags

cmdline/stress.c, src/mrarray-private.h, src/mrarray.c, src/mrarray.h, src/mrmailbox-private.h, src/mrmailbox.c, src/mrmailbox_internal.h, src/mrmailbox_receive_imf.c, src/mrsqlite3.c, src/mrtools.c, src/mrtools.h
see https://github.com/deltachat/deltachat-core/issues/69#issuecomment-370247669 for details about this PR
=> Support Ad-hoc groups

src/mrcontact-private.h
Thanks r10s for explaining (https://github.com/deltachat/deltachat-core/commit/08611fac233109695eed8c990b35875aa146bfbc#commitcomment-28451341)
=> explaining comment

src/mrmimefactory.c
=> encode filenames in 'Content-Disposition: ... filename=...' wrt RFC 2047

cmdline/cmdline.c, cmdline/main.c, src/mrevent.h, src/mrimap.c, src/mrimap.h, src/mrjob.c, src/mrjob.h, src/mrmailbox-private.h, src/mrmailbox.c, src/mrmailbox.h, src/mrmailbox_configure.c, src/mrmailbox_connect.c, src/mrmailbox_log.c, src/mrsmtp.c, src/mrsqlite3.c
- it's up to the caller to create the thread needed for idle
- if needed, it's up to the caller to handle wakelocks
=> Caller idle

src/mrimap.c
The mailserver of @Ji-eF does not work with the used MOVE command, so messages are left in the INBOX (see deltachat/deltachat-android#307).
I found the hint in the source that many mailservers don't support the MOVE operation so we should fallback to COPY/DELETE.
This is my first attempt to do that. The copy part works, however the delete part does not.
EDITED. See below
The String from the test-server is:
```
IMAP-Capabilities: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT IDLE CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS QUOTA
=> Fallback to Copy/Delete if Move not possible

src/mrmailbox_imex.c
When I export my GPG Key via Thunderbird/Enigmail (after I removed the passphrase), it creates a single .asc file which contains the public and private key.
This patch allows DC to also import such files. Since it only comes into action when the file starts with a public key, this should not break anything, eventhough it might not work in all cases.
Related to #36 (which is IMHO not fixed) and https://github.com/deltachat/deltachat-android/issues/98
=> Fix: Import keys where public and private key are in the same file

src/mrjob.c
should fix https://github.com/deltachat/deltachat-android/issues/337
=> do not wait for 'no time' in the smtp-idle (may result in heavy load)

src/dc_context.c
Corrected Info message from "context requests" to "contact requests"
=> context requests -> contact requests

README.md
Using the same style in `deltachat-node`.
=> Link to LICENSE

cmdline/main.c, src/dc_chat.c, src/dc_imex.c, src/dc_job.c, src/dc_mimefactory.c, src/dc_mimeparser.c, src/dc_msg.c, src/dc_sqlite3.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h
=> move outgoing files to blobdir; use relative paths for blobdirs.

src/dc_configure.c
this should allow connection with default dovecot installations that seem to use the part before the `@` as the login name.
probably, there are also other servers around that work this way.
if IMAP-login succeeds with the username, however, we use the same username for the SMTP-login. if this would require the full email-address then, this has to be provided explicitly in the credential screen or via autoconfig.
=> let dc_configure() also try to use localpart of email-address as loginame

src/meson.build
=> Do not install internal header files

src/dc_chat.c
see [dc_msg_get_state()](https://deltachat.github.io/api/classdc__msg__t.html#a83fbf6e74d09a0b598ccefe9b48bd68c) for some more info about fresh/noticed/seen messages.
=> mark messages of chats being archived as noticed

python/.gitignore, python/doc/_templates/globaltoc.html, python/doc/_templates/sidebarintro.html, python/doc/api.rst, python/doc/capi.rst, python/doc/conf.py, python/doc/examples.rst, python/doc/index.rst, python/doc/install.rst, python/liveconfig.txt, python/src/deltachat/__init__.py, python/src/deltachat/account.py, python/src/deltachat/chatting.py, python/src/deltachat/cutil.py
see online snapshot: https://m.devpi.net/hpk/dev/deltachat/0.5.dev0/+doc/index.html
=> improve docs and structure

.scripts/deploy.sh, .travis.yml, python/src/deltachat/__init__.py
simplify doc building, cc @azul
=> tox already cares for doc-building

.scripts/deploy.sh
=> travis-push c-docs to new https://c.delta.chat site

.travis.yml
Fixed the ppa issue.
However this still only gives us doxygen 1.8.7, while @hpk42 said we need 1.8.11.
Looks like there is no ppa for 1.8.11: https://www.ubuntuupdates.org/pm/doxygen
=> Try doxygen new

README.md
the repo also contains the python bindings.
=> actually also mention the python bindings up front because

libs/netpgp/src/keyring.c, libs/netpgp/src/packet-parse.c
add some resilience against bad input parameter to netpgp.
may solve the problem with #333
=> check for some NULL-pointers in netpgp

libs/cyrussasl/meson.build, libs/libetpan/meson.build, libs/netpgp/meson.build
Supersedes https://github.com/deltachat/deltachat-core/pull/346
=> Neppgp ssl mac

src/dc_array.c, src/dc_chat.c, src/dc_chatlist.c, src/dc_contact.c, src/dc_context.c, src/dc_lot.c, src/dc_msg.c
just some comments, no behavouir changes.
=> comment some behaviours or NULL arguments and NULL return values

CHANGELOG.md, src/deltachat.h
=> bump version, changelog

python/src/deltachat/__init__.py, python/src/deltachat/message.py, python/tests/test_account.py, src/dc_msg.c, src/deltachat.h
dc_msg_get_received_timestamp() can be used to find out the receiving time of a message.
=> add a function to get the receive time of a message

python/CHANGELOG, python/src/deltachat/__init__.py, python/src/deltachat/account.py, python/src/deltachat/message.py, python/tests/test_account.py
also simplify creating a mime object from the headers ...
=> move get_mime_headers() function to Message object where it belongs.

src/dc_chat.c
just some more lines to document the use of this function :)
=> refine comment for dc_chat_is_unpromoted()

cmdline/main.c, cmdline/stress.c, src/dc_chat.c, src/dc_receive_imf.c, src/dc_stock.c, src/dc_stock.h, src/deltachat.h
- merge DC_STR_GET_STRING and DC_STR_GET_QUANTITY_STRING into DC_STR_GET_STRING(strId, quantity)
- move DC_STR_* constants to deltachat.h
closes #410
=> Simplify and unify string handling

src/dc_context.c
=> Check key name on dc_set_config() and dc_get_config()

.github/ISSUE_TEMPLATE.md
stolen back from https://github.com/deltachat/deltachat-desktop/pull/320 :)
=> less verbose issue-template

src/dc_configure.c, src/dc_context.h
=> refine dc_configure() doc

src/dc_receive_imf.c
while [dc_set_chat_profile_image()](https://c.delta.chat/classdc__context__t.html#a9173428fc8f5727a04db2172a9aaa044) sends out the images [as expected](https://github.com/deltachat/spec/blob/master/spec.md#set-group-image) there was a bug when parsing the incoming messages:
- the group messages was expected to have 2 parsed parts (text and image), however, through the new compound messages, it results just in an image with description).
this pr just uses the first image from messages containing a `Chat-Group-Image` header as the new group image unless the value of the header is `0` (in this case the group image is deleted)
closes https://github.com/deltachat/deltachat-desktop/issues/273
=> make dc_set_chat_profile_image() work again for remote recipients

src/dc_mimefactory.c
fixes #487, thanks @Simon-Laux
=> allow sending files without suffix

src/dc_chat.c
to get a clue to why a group is not encrypted, this pr adds loglines for missing peerstates and non-mutual peerstates.
this may be improved by ui elements, system messages or whatever and is releated to other decisions. however, for now it allows at least to find out the reason.
=> log missing peerstates and non-mutual peerstates

src/dc_mimeparser.c, src/dc_msg.c, src/dc_tools.h
=> show summary for images and other documents

src/dc_chat.c, src/dc_mimefactory.c, src/dc_receive_imf.c, src/dc_stock.c, src/dc_stock.h, src/deltachat.h
closes https://github.com/deltachat/deltachat-android-ii/issues/215, closes #220
=> improve status messages

src/dc_receive_imf.c
this pr modifies [check_verified_properties()](https://github.com/deltachat/deltachat-core/compare/selfpeer?expand=1#diff-1d2adc03d043975786fd5caef8655673R492) and skips the peerstate check if the message was sent by SELF.
this fixes potential group-splits in a multi-device setup as the SELF-peerstate is not really tracked nor needed.
as an alternative, we could also track the peerstate for SELF and leave the test as id, however, this would affect much more code and is not really needed afaik.
tackles #413
=> treat SELF-peer as being verified to avoid group-splits

src/dc_context.c
closes https://github.com/deltachat/deltachat-android/issues/666
=> handle selfstatus default values in the core

src/dc_configure.c
This change is targeting #545.
Partially reverting [this commit](https://github.com/deltachat/deltachat-core/commit/a128a0ed694473867998e0d0776446f53b3e2ce4?diff=unified).
=> Add emailaddress to http autoconfig request

src/dc_chat.c
=> limit the number of messages referenced

cmdline/stress.c, src/dc_mimeparser.c, src/dc_simplify.c, src/dc_simplify.h
closes #517, however due to some larger changes in parsing, i would not merge this to master while we're in january-release
=> crop ">" only for other muas

src/dc_configure.c
this pr improves the autoconfiguration by probing STARTTLS on port 993 after probing SSL on 993.
if both fail, both are retried with using only the local part of the mail as the login name.
closes #552
=> probe imap STARTTLS on ports 993 and 143

.gitignore, README.md, cmdline/stress.c, deltachat-core.cbp, meson.build, meson_options.txt, src/dc_context.c, src/dc_context.h, src/dc_imex.c, src/dc_pgp.c, src/dc_pgp.h, src/dc_receive_imf.c, src/deltachat.h, src/meson.build
This expects rpgp to be installed using the following work flow
```
> git clone https://github.com/dignifiedquire/rpgp
> cd rpgp/pgp-ffi
> make install
```
After that run `meson && ninja` and things should build. 
Current  state: 
- Stress tests are passing, and the cmdline cli boots up
- All required things are in `master` of rpgp
=> Add experimental support rPGP 

src/dc_imex.c, src/dc_key.c
targets https://github.com/deltachat/deltachat-desktop/pull/707#issuecomment-470739734
=> trigger DC_EVENT_IMEX_FILE_WRITTEN on successful writes

src/dc_location.c
this send DC_EVENT_LOCATION_CHANGED which is needed to update the map
=> return the correct value from dc_save_locations()

src/dc_context.h, src/dc_location.c, src/dc_receive_imf.c, src/dc_sqlite3.c, src/dc_sqlite3.h
this pr saves SELF-location per chat and closes https://github.com/deltachat/deltachat-core/issues/617
moreover, the correct messages-id is stored for incoming locations
@cyBerta feel free to merge :)
=> refine location streaming

cmdline/stress.c, src/dc_context.c, src/dc_location.c, src/dc_tools.c, src/dc_tools.h
@nicodh please give it a try and merge if it works on mac :)
fixes #631, partly reverts https://github.com/deltachat/deltachat-core/pull/618
=> hack around floating point atof() and printf(%f)

src/dc_msg.c
closes https://github.com/deltachat/deltachat-android/issues/748
should make https://github.com/deltachat/deltachat-android/pull/798 superfluous
=> handle image/webp files

src/dc_msg.c
closes https://github.com/deltachat/deltachat-android/issues/738
@Boehrsi again, feel free to merge :)
=> handle text/vcard files

cmdline/cmdline.c, src/dc_array.c, src/dc_context.h, src/dc_location.c, src/deltachat.h
introduce the function `dc_array_get_chat_id(location_array, index)`
please note that for older location-streams this id may be 0.
=> get the chat-id belonging to a location

cmdline/cmdline.c, cmdline/stress.c, src/dc_array.c, src/dc_context.h, src/dc_location.c, src/dc_mimefactory.c, src/dc_mimefactory.h, src/dc_mimeparser.c, src/dc_msg.c, src/dc_receive_imf.c, src/dc_stock.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h
=> tweak location streaming

cmdline/cmdline.c, src/dc_chat.c, src/dc_chat.h, src/dc_context.h, src/dc_job.c, src/dc_job.h, src/dc_location.c, src/deltachat.h
=> add dc_chat_is_sending_locations()

python/setup.py
=> Break looping through __init__.py lines in read_metadata() after version string is found

meson.build
Git diff isn't smart enough to show the actual changes.  It's all just wrapped in an if statement really.
=> support newest libetpan using pkg-config

src/dc_receive_imf.c
closes https://github.com/deltachat/deltachat-android/issues/980
=> show asm independingly of show-emails settings

src/dc_chat.c
basically "back port" https://github.com/deltachat/deltachat-core-rust/pull/288
=> fix deltachat/deltachat-core-rust/issues/163
