libs/netpgp/meson.build
This makes sure that at meson/configure time the build will fail
with an error saying the library can't be found.  This is much
better then a mysterious link error right at the end of the
compilation.
=> Make libbz2 a proper dependency

python/setup.py, python/src/deltachat/_build.py, src/mrmailbox.h, src/mrmsg.h
DO NOT MERGE
This is a very rough first stab at compiling CFFI Python bindings for deltachat-core.  It compiles and generates some bindings, but that's about it.
1. I've done this as a PR in this repo instead of a new one.  It makes header modifications easier and means I don't have to worry about copyrights.  It may even make sense to leave the raw bindings here but it can always be moved out later.
2. This runs the header files through the preprocessor (`gcc -E`) using the `PY_CFFI` symbol to end up with something which is parsable by cffi.  I think this will stay but the implementation cleaned up somewhat and the number of ifdefs reduced.
3. I've effectively made the structs opaque/private for cffi.  I did this as otherwise I had to worry about defining opaque structs for pthread_t and …
=> WIP: First step towards python bindings

src/mrimap.c, src/mrimap.h
- avoid deleting the wrong message if UIDVALIDITY has changed
- in the future, we may SEARCH for the message-id if folder/UID does not point to the correct one
=> Check msgid before delete

src/mrmailbox.h, src/mrmailbox_configure.c, src/mrmailbox_oob.c, src/mrmimefactory.c, src/mrparam.h
search for autoconfig also in example.com/.well-known/autoconfig/mail dir
refers to  https://github.com/deltachat/deltachat-core/commit/5cee73a750091d3a20b645fd37ca7863573f3e3e#commitcomment-28308841
regarding the `emailaddress=` parameter:
the [doc](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration) does not mention it, however, Thunderbird uses it, at least in the [source code](https://releases.mozilla.org/pub/thunderbird/) 45.5.1. as it makes some sense, i do not think, this has changed: the .well-known dir is for users who cannot add a subdomain - why not give them the same options (to return eg. customized login names) as for the subdomain solution.
looking at the thunderbird source code, i am also wondering, why they do not look at the https domains, …
=> improve autoconfig

src/meson.build, src/mrerror.h, src/mrevent.h, src/mrmailbox-private.h, src/mrmailbox.h, src/mrmailbox_e2ee.c, src/mrmailbox_oob.c, src/mrmimefactory.c
moving sensible headers from the unencrypted part to the header of the encrypted payload.
headers moved are: `Subject`, the `Secure-Join`-headers (used for the newQR code verification) and all `Chat-` headers (but  `Chat-Version` as there is a rough idea that this can be used for filtering).
moreover, the `Autocrypt-Gossip` headers are also moved here.
nb: older Delta Chat versions can read these headers already since [v0.11.4](https://github.com/deltachat/deltachat-android/blob/master/CHANGELOG.md#v0114)
information: https://github.com/autocrypt/memoryhole/ (this doc really needs some maintenance)
maybe in the future further headers can be moved to the encrypted part, however, this needs some discussions wirh the memoryhole people; however, at least, the code is now there :)
=> Write memoryhole

src/mrchatlist.c, src/mrcontact.h, src/mrmailbox.c, src/mrmailbox_oob.c, src/mrmailbox_receive_imf.c, src/mrmsg-private.h, src/mrmsg.c, src/mrsqlite3.c
hidden messages are needed as the handshake messages for the secure-join messages sent after a QR scan should not appear in the normal chats. Instead, a resulting "system message" as "contact verified" or so should appear.
btw: an alternative to hiding messages would be to allow sending normal MIME-messages without the database background, however, this seems even more complicated as the current approach offers contact_ids, easy deletion and so on. and hiding messages may get handy for other things, too.
=> support hidden messages

cmdline/main.c
allow curl to perform "insecure" SSL connections using flag '--insecure'
Without this flag, curl exited with error 51: The peer's SSL certificate or SSH MD5 fingerprint was not OK.
autoconfig attempts to https URLs did not succeed.
=> allow curl to perform "insecure" SSL connections

README.md
I tried to follow the instruction, however Ubuntu 16.04 has a version of meson that seems to be too old.
Googling for the error I found https://github.com/haecker-felix/gradio/issues/183 which pointed me to the solution.
Installation worked with 0.45.1.
Not sure whether 0.36.0 is sufficient.
=> meson: at least version 0.36.0

src/mrmimeparser.c
Otherwise, if mimeparser is NULL, "goto cleanup" is triggered and
uninitialized pointer will be freed.
clang warns about this during compilation.
=> initialize from_addr_norm with NULL

src/mrchat-private.h, src/mrimap.c
This fixes https://github.com/deltachat/deltachat-android/issues/103 and probably other providers (maybe https://github.com/deltachat/deltachat-android/issues/28).
If it is not possible to create the folder `Chats` we also try `INBOX.Chats` and use this if creation succeeds. I tested this on a fresh domain factory account and it works.
=> Use INBOX.Chats as fallback if Chats can't be created

src/mrchat-private.h, src/mrimap.c, src/mrimap.h
Instead of using hardcoded `INBOX.Chats` as fallback if `Chats` can't be created (#173) we detect the IMAP folder-delimiter as part of the list folders process and use this to construct the fallback folder name.
Please review if I did everything correct with C strings, because I am not that familiar with C and don't want to introduce security holes.
=> Feature: Detect IMAP separator for INBOX subfolder

src/mrsmtp.c
This commit retries the SMTP login if the method is PLAIN and it failed. See deltachat/deltachat-android#67 for details.
=> Workaround for hMail. Fixes deltachat/deltachat-android#67

meson.build
This was comparing a list with a string, which will start failing in
the future (as it should!).  But there's simply no need for this,
declare_dependency() function is quite happy with an empty list for
argument.  This was probably a leftover from an earlier attempt to get
things working.
=> Fix etpan deps creation

meson.build
I am working on a plugin using deltachat-core. this patch makes meson create a pkg-config file so my library can make use of it easily.
=> patch makes meson create pkg-config file so apps can make use of it

.gitignore, python/src/deltachat/_build.py, python/tests/test_mrmailbox.py, src/deltachat.h
This fixes the python bindings build to work with the new layout of
the header files and new names.
=> Update python bindings to new headers naming

python/src/deltachat/__init__.py, python/src/deltachat/_build.py, python/tests/conftest.py, python/tests/test_mrmailbox.py
This uses one global event handler function on the C level, as
enforced by CFFI, and caters for registering a per-context event
handeler.  A simple fixture for doing this during tests is also
implemented.
/cc @hpk42
=> Add support for the callback in python/cffi

src/dc_chatlist.c, src/deltachat.h
this is a helper for the UI creating the chatlist.
already today, the chatlist consist out of normal chats identified by an ID _plus_ some special IDs representing special items. currently, these items are the "Archive" link and the "Contact requests".
UIs as the new signal port show a help-hint if everything is archived (sth. as _"well done, nothing more to do ... you have a zero inbox"_. to help these UIs adding such an item to the virtual "recycler" view - which is typically complicated enough - this pr offers an option to easily add such an item as needed:
if the flag `DC_GCL_ADD_ALLDONE_HINT` is given to `dc_get_chatlist()` and there are no but archived chats, the item `DC_CHAT_ID_ALLDONE` is added; typically together with the "Archive" link.
=> Add option to add a special marker for "All done" to the chatlist

python/setup.py, python/src/deltachat/__init__.py, python/src/deltachat/account.py, python/src/deltachat/myattr.py, python/src/deltachat/types.py, python/tests/test_account.py, python/tox.ini
address #273 -- also refine the GC-handling of contact and message pointers.
free-ing dc_context pointers kind of works now -- but without calling account.shutdown() first 
then GC ``__del__`` calls could end up without access to globals. Refining/reviewing GC handling should mostly be part of a separate effort than this PR.  The current PR is at least an improvement.
=>  introduce attr / refine GC handling

cmdline/stress.c, src/dc_aheader.c, src/dc_contact.c, src/dc_qr.c, src/deltachat.h
added two functions:
- `dc_lookup_contact_id_by_addr()` checks if an e-mail-address is in the database (wondering that this function does not exist :)
- `dc_may_be_valid_addr()` is used internally to check addresses eg. given to dc_create_contact(). thought that i would need it for the new android port, however, it's not needed. nevertheless, it may be useful here and there - esp. as it is the same logic as used internally to validate addresses.
nb: the validation is rather generous, however, doing more complex regex things will increase problems but probably not solve some. validating email addresses "the right way" seems to be very hard, see eg. https://www.regular-expressions.info/email.html
=> lookup contacts

cmdline/stress.c, src/dc_tools.c
moreover, if there is no  but it is shall be used, the corresponding function fail.
typically, this may only happen when testing the file functions directly - when using through the documented functions, there is always a blobdir if dc_open() succeeds. however, it is better, to have another security layer when creating the absolute pages.
=> test file functions with  only if there is a blobdir

src/dc_contact.c
`DC_CONTACT_ID_SELF` is used for the configured contact address nearly everywhere, so also `dc_lookup_contact_id_by_addr()` should return this value when looking up the own address.
=> looking up contact-ids returns DC_CONTACT_ID_SELF for the own address

src/dc_configure.c
iirc, these "high" progress events came from some searching for weird bugs...
=> cleanup configure-cleanup, do not show a progress of 99% if we're about to fail

src/dc_configure.c, src/deltachat.h
up to now, "Cannot read file" errors are only printed when DC_EVENT_HTTP_GET returns NULL.
if an empty string was returned, deltachat-core tries to parse this as xml content - which, of course, also results in an error some time later.
from the view of deltachat-core, there is no need to distinguish between NULL or an empty string.
so, this pr accepts empty strings explicitly as an error and also documents be behavior so that it is easier for bindings to return this error state.
@ralphtheninja when this is merged, i think we can remove the explicit handling of empty stirngs in [dcn_set_http_get_response](https://github.com/deltachat/deltachat-node/blob/master/src/module.c#L1331)
=> explicitly handle empty strings received from the UI on DC_EVENT_HTTP_GET

python/conftest.py, python/src/deltachat/__init__.py, python/src/deltachat/account.py, python/src/deltachat/chatting.py, python/src/deltachat/cutil.py, python/tests/test_account.py
- refactor gc-handling wrt to array
- don't cache dc_chat and dc_msg and dc_contact structs -- "if in doubt, don't cache" as the wise programmers say. and i am not sure we need it.  the caching was also there to handle GC things but now that we have "ffi.gc()" we don't need that 
- add some high level APIs (forwarding messages, setting chat names, creating group chats and getting all chats ... but the latter are very simple chats for now, do not expose the full underlying API)
- improve some doc strings
=> add some more high-level API, and tests

src/dc_chat.c, src/dc_msg.c, src/dc_sqlite3.c
- send DC_EVENT_MSGS_CHANGED on marking as noticed only on changes:
typically, the UI calls dc_marknoticed_chat()  whenever a chat is opened and reacts on a redraw when the DC_EVENT_MSGS_CHANGED is received. this change avoids superfluous redraws.
- send DC_EVENT_MSGS_CHANGED on deletion of messages
this was just missing :)
=> improve some msgs-changed events

README.md
- remove feature descrpition
- focus on build instructions 
- shorten some section (eg don't explain GPL)
=> Shorter more focused readme

python/conftest.py, python/src/deltachat/account.py, python/tests/test_account.py, python/tox.ini
- refine config API 
- allow pseudo-configured accounts for tests 
- introduce ``Account.configure(**kwargs)`` and ``Account.set_config(name, value)``
- tie freeing of "dc_context" objects to ffi.gc() logic
=> Config api refinement, better test setup

src/dc_context.h, src/dc_job.c
to allow dc_configure() being called without the threads being started, we suspend the smtp-thread now by checking that we're not in performing jobs instead of waiting for entering idle.
closes #304 if being merged
=> suspend smtp-thread by waiting-for-job-finish instead of entering-idle

src/dc_context.c, src/dc_sqlite3.c
let open return an error if there is already an opened database, fixes #308 and relates to https://github.com/deltachat/deltachat-desktop/issues/61
=> let open return an error if there is already an opened database

.travis.yml
This builds on top of #321 .
Instead of having a install step that fetches apt packages we can just do all of this in the apt addon.
Also renamed the before_install step to install now.
=> Make more use of apt addon

src/dc_configure.c, src/dc_imex.c, src/deltachat.h
the reason is a better support for older doxygen versions, closes #323
=> use tilde instead of backtick for code fencing

meson.build, meson_options.txt
Since we do not have access to the value of wrap-mode we can not
make the etpan dependency to behave correctly.  Hack around it by
introducing a new option just for etpan.
@ralphtheninja this would need your node bindings to use the new -Dforce-etpan-fallback=true as well as --wrap-mode=forcefallback.  But would mean it should correctly ignore the system one.  What do you think?
=> Hack around libetpan not respecting wrap-mode

src/dc_sqlite3.c
currently, transactions are used at some places.
the transactions are _not_ needed to create compound statements that must not be executed imcomplete.
the transactions were only added in the hope that things should go faster.
however, esp. for threads, transactions have their complexity. eg. they must not be nested in the same thread and may fail if a transaction in another thread takes too much time, see also the [comment atop of dc_sqlite3.c](https://github.com/deltachat/deltachat-core/blob/master/src/dc_sqlite3.c#L28).
as i also do not see speed improvements worth this challenge, i would suggest to disable transations for now.
=> disable transactions

src/dc_configure.c, src/dc_imap.c
we simplify the dc_is_configured() function to just check for the corresponding flag in the database.
this should be fast enough, esp. as the function is typically only called on program startup.
assumptions that an imap-connection always implies a correctly configured account may be wrong (eg. during configuration imap may be fine but smpt fails later on so that we're never configured although imap was working a while)
=> remove unnecessary assumptions about configured-state

src/dc_context.c
Closes https://github.com/deltachat/deltachat-core/issues/348
* use key=value format
* all keys are lower case
* one key/value pair per line
* better naming of some keys
Current format:
```
deltachat_core_version=v0.20.0
sqlite_version=3.22.0
sqlite_thread_safe=1
libetpan_version=1.8
openssl_version=1.0.2n
compile_date=Oct  7 2018, 01:49:02
arch=64
number_of_chats=0
number_of_chat_messages=0
messages_in_contact_requests=0
number_of_contacts=0
database_dir=/tmp/8433c0c3d49135d0250663104b07e2da/db.sqlite
database_version=41
blobdir=/tmp/8433c0c3d49135d0250663104b07e2da/db.sqlite-blobs
display_name=Delta One
is_configured=1
entered_account_settings=delta1@delta.localhost delta1:***:127.0.0.1:3143 delta1:***:127.0.0.1:3025 IMAP_PLAIN SMTP_PLAIN
used_account_settings=delta1@delta.localhost …
```
=> Normalize output from dc_get_info()

src/dc_chat.c, src/dc_chatlist.c, src/dc_imex.c, src/dc_job.c, src/dc_mimefactory.c, src/dc_msg.c, src/dc_msg.h, src/dc_securejoin.c, src/deltachat.h, src/mrmailbox.h
- force dc_msg_new() to take the view type
- remove dc_msg_set_type()
- dc_msg_get_type() renamed to dc_msg_get_viewtype() (not: view_type)
- mark dc_send_X_msg() as being deprecated (would like to remove them soon)
=> slightly rework message sending 

src/dc_mimeparser.c, src/dc_msg.c, src/deltachat.h, src/mrmailbox.h
just remove the DC_MSG_UNDEFINED viewtype from the API.
internally, 0=undefined is still used, but it is no longer valid for input from the API and is no longer returned.
=> remove DC_MSG_UNDEFINED from API

src/dc_contact.c
calling dc_add_address_book() results in a DC_EVENT_CONTACTS_CHANGED now - analogue to dc_create_contact(), dc_delete_contact() and so on.
the event was just missing :)
changes in the bindings are not needed :)
=> send DC_EVENT_CONTACTS_CHANGED on adding address book

cmdline/cmdline.c, cmdline/stress.c, python/src/deltachat/account.py, src/dc_context.c, src/deltachat.h
dc_get_config() return the appropriate default parameter automatically if no value was set before.
NULL is never returned.
closes #367 
EDIT: of course, travis does not built because of the changed function signature :)
=> remove default-parameter from dc_get_config()

libs/netpgp/meson.build
We can not use cc.has_header() when using a fallback, but we know
the fallback so can just set things correctly for it.
fixes #350
=> Fix usage of netpgp fallback libs

libs/netpgp/src/openssl_crypto.c, src/dc_pgp.c
while figuring out the slowness of openssl, see #376, i came across an probably unused debug routine that takes up ~ 500 ms on each message sending, it's in the message signing-part (not encryption as the function name may suggest).
as the message cannot go to smtp before it is signed and encrypted, the whole sending process is delayed by just this time.
moreover, this pr adds an info line to the log that shows the time needed for signing and encryption. for me unexpectedly, the encryption is more than 50 times faster than the signing.
(all times refer to my nexus 4 testing device and to a short text message of a few words)
=> speed up messages sending

cmdline/cmdline.c, src/dc_chat.c, src/dc_mimefactory.c, src/dc_mimeparser.c, src/dc_msg.h, src/dc_sqlite3.c, src/deltachat.h
this pr makes deletachat-core able to add text to images/file/music/voice messages.
the text is added to the message object as usual using `dc_msg_set_text()`.
receiving such messages is also straight forward: _any_ message type can now contain text that can be retrieved using `dc_msg_get_text()`. 
this change makes it much easier to add some lines of text to a file.
the added text also appears smart together with the image/file in non-delta-muas. 
to allow the old telegram-ui to show these new compound messages without changes, i've added the function dc_no_compound_msgs() that let the core generate single messages for the description, however, this function is not documented and will be removed soon. all UIs should just be able to show the text attached to files.
btw. i do not think …
=> allow text added to images/files/etc.

CHANGELOG.md, cmdline/stress.c, src/dc_chat.c, src/dc_job.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h
this pr copies files before dc_msg_send() returns instead of postponing the copy action to the smtp-thread.
as files given to dc_msg_send() are no longer needed after dc_msg_send() returns, the event DC_EVENT_FILE_COPIED is no longer needed (eg. files can be deleted at once and without waiting for an event).
this change should make the overall usage of the sending message API easier and closes #374
=> copy files before dc_msg_send() returns

src/dc_context.c, src/dc_context.h, src/dc_log.c
the remaining return value of dc_get_info() are plain key=value lines, so i also removed the initial headline.
i did not add a special function for getting the log excerpt back in another way; if needed by some implementation, these could easily do the stuff that is removed in this pr in their callbacks, however, i think for most implementations not even this is needed as the "delta log lines" may be retrieved in the system log - together with other, non-delta, valuable information.
closes #386
=> remove log excerpt from dc_get_info()

python/setup.py, python/src/deltachat/account.py, python/tests/test_account.py, src/dc_context.c, src/dc_job.c, src/dc_msg.c, src/dc_receive_imf.c, src/dc_sqlite3.c, src/deltachat.h
- add a new function to get the mime-headers of messages, currently incoming only, dc_get_mime_headers()
- to collect the headers so that the function can word, one has to set the flag `save_mime_headers` using dc_set_config()
in contrast to my proposal in #365, i save the headers in a database as i do not want to mix files of too many different sources in the blob directory.
=> add a switch and a function to get mime-headers

src/dc_mimeparser.c
since pr #384, the core allows compound messages of text+attachment.
this pr fixes an issue where for voice messages, the text part was reset to "ogg" (comes from legacy fulltext search code that allows to search for extensions, in recent versions of Delta Chat the "txt" field is just always displayed to the user in the ui)
=> do not overwrite the text of voice-text-compound-messages

cmdline/stress.c, src/dc_lot.c, src/dc_mimefactory.c, src/dc_mimeparser.c, src/dc_msg.c, src/dc_msg.h, src/dc_param.h, src/deltachat.h
this pr removes the functions dc_msg_get_mediainfo() and dc_msg_set_mediainfo() that was meant to be used to set an author and a trackname for a media file.
however, i think these functions were a bit overambitious. also they are not well supported. eg. the information are written partly to the filename and also read from there as there is no easy way to pass them to a media file (id3 is too special).
also these functions were very special - they are only used when sending mp3 music files - might me that i was too close to my old silverjuke-project in the beginning :)
finally, only author and trackname are not even suffient, to do things right, we would need probably much more.
so - i would suggest to remove them. it seems to be totally fine to display the filename of mp3 files - as done …
=> remove untidy and incomplete mediainfo functions

src/dc_msg.c
the message summaries for audio-files and other files show sth. as `File: name.ext` or `Audio: name.ext`.
this pr fixes a bug where the path was shown in the summary as `Audio: $BLOBDIR/name.ext`
=> remove path from audio-summary, show filename only

src/dc_stock.c
Correct me if I'm wrong, but this message is sent out to the group from a member when _they_ leave the group, right? To me "Group left" means that it was the group that left and not the member.
=> Tweak DC_STR_MSGGROUPLEFT default message

.gitignore, python/setup.py, python/src/deltachat/_build.py, python/src/deltachat/chatting.py, python/src/deltachat/message.py, python/src/deltachat/props.py, python/tests/conftest.py
- This renames deltachat.types to deltachat.props.  Not re-using a
stdlib name is somewhat nice and solves a weird edge-case for me where
the deltachat.types module can be hiding stdlib types by the deltachat
directory appearing before the stlib on sys.path.
- When manually invoking the build script (rather then via
pip/setup.py) it figures out where the package actually lives and
makes sure the .so file ends up in that directory.  This is better
than the current version which depends on the current directory and
thus sometimes creates an alternate deltachat/ directory tree.
- Add some common python artefact files to gitignore.
=> Improve building of extension a little

cmdline/stress.c, src/dc_chat.c, src/dc_configure.c, src/dc_context.c, src/dc_imap.c, src/dc_imap.h, src/dc_job.c, src/dc_job.h, src/dc_loginparam.c, src/dc_mimefactory.c, src/dc_mimefactory.h, src/dc_param.h, src/dc_receive_imf.c, src/dc_sqlite3.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h
- tackle #370 by forcing SELF being always on the recipient list
- tackle #370 by completely removing the call to the IMAP upload
- #371 is also tackled as the messages that arrive in the INBOX now are not moved to DeltaChat folder. EDIT: by 0123a064f9c6208d987df4a0b4c83b2d3863ea9c this is also true for incoming messages
to keep the changes more clear, currently reformatting is skipped; this can be done later. as well as removing dead code.
messages are not appearing twice as there is already a check for the Message-ID in dc_receive_imf(), so, for now, this is fine. later on, we can optimize this by checking the Message-ID without completely downloading the whole message.
closes #370, closes #371, closes #372, closes #72
=> steps towards single-folder milestone

.travis.yml, src/dc_context.c
- do not return special chat_ids to the list (this was not notices in the old telegram-ui as the list was compared against the messages arrived through DC_EVENT_INCOMING_MSG, however, what should not be necessary)
- do not return NULL on errors, instead, return the empty list as also done for other functions
- add a bit more of documentation
=> make dc_get_fresh_msgs() more reliable

cmdline/cmdline.c, meson.build, src/dc_context.h, src/dc_job.c, src/dc_job.h, src/dc_param.h, src/dc_sqlite3.c, src/deltachat.h, src/meson.build
make the retries on failures more reliable, see https://en.wikipedia.org/wiki/Exponential_backoff.
- the calculation of the backoff times is done in [get_backoff_time_offset()](https://github.com/deltachat/deltachat-core/pull/417/files#diff-3f291e506d02f02b7f7e2e9ba43234b4R413) which is based on the [playground-python-snippet](https://github.com/deltachat/playground/blob/master/expbackoff/compute.py)
- we use a MULTIPLY of 5 which results in random retries in the following intervals in seconds: [0..5] [0..15] [0..35] [0..75] [0..155] [0..315] [0..635] [0..1275] [0..2555] [0..5115] [0..10235] [0..20475] [0..40955] [0..81915] [0..163835] (the last one is about max. 2 days, we stop after 16 retries)
- we introduce a new function (o/ @ralphtheninja) called …
=> use exponential backoff

src/dc_chat.c
SELF-talks are mainly used to transfer data between devices, eg. Autocrypt Setup Messages.
have these messages attached somewhere to a thread does not make much sense.
=> do not set In-Reply-To/References for SELF talks, closes #431

src/dc_configure.c, src/dc_context.h, src/dc_imap.c, src/dc_job.c, src/dc_log.c, src/dc_securejoin.c, src/dc_smtp.c, src/dc_stock.c, src/deltachat.h
this pr stops using DC_EVENT_IS_OFFLINE to decide if to connect or to retry a job.
instead, the network action is just performed and if it fails, well, we know that.
there is one remaining usage of DC_EVENT_IS_OFFLINE: _if_ an network error occurred, only the first one is reported as an error that should be shown to the user (via DC_EVENT_ERROR) - if there is not network in that moment we say just "No Network" to the user instead of sth. as "Login with password xyz" failed as the latter is probably misleading. however, the latter is still logged as a warning.
closes #426
closes https://github.com/deltachat/deltachat-android-ii/issues/127
also tackles #293 a bit
=> remove DC_EVENT_IS_OFFLINE

src/dc_imap.c
due to exponential backoff and dc_maybe_network(), we can process jobs at any time now, very short IMAP-timeouts are no longer needed (the 1 minute came from the need to process jobs in a very simple way); reset to 23 minutes as before imap/smtp-thrad-split
in addition to that, the UI can call dc_interrupt_imap_idle() at any time (to protect against  NAT Gateway timeout? not sure, but needed eg. in Android for any reason, cmp. https://www.isode.com/whitepapers/imap-idle.html)
=> use longer IMAP-idle timeout

src/dc_chat.c, src/dc_context.h, src/dc_log.c, src/dc_stock.c, src/deltachat.h
- remove data1 parameter from DC_EVENT_ERROR which is now in sync with DC_EVENT_WARNING|INFO. this allows easier conversion to specific events.
- turn DC_EVENT_ERROR(SELF_NOT_IN_GROUP) into DC_EVENT_ERROR_SELF_NOT_IN_GROUP(msg)
- dc_log_error(msg) is now simply a shortcut for  dc_log_event(DC_EVENT_ERROR, msg); same for dc_log_info|warning()
theoretically, we can remove the data1 parameter from dc_log_event|info|warning|error(), it is unused and always 0 is passed.  
however, not sure if we use it for different purposes (maybe translation-string-id?), so, instead of changing thousand lines or so, i suggest to wait and see for now :)
tackles #293
=> simplify events

cmdline/main.c, src/dc_log.c
- the detailed error string on network messages was accidentally not forwarded to DC_EVENT_ERROR_NETWORK; instead the string "event #401" was shown
- log the new events in the command line tool
=> print new events

src/dc_job.c
tweaking/fixing  get_backoff_time_offset():
- moved the `- 1` to the exponent (probably a typo, does not make really sense outside the bracket imho) so that the first retry is within a minute (2^0  = 1)
- to keep the max. timespan, increased the number of retries by one
- move the MULTIPLY in front of the randomization; before, every first-retry was exactly either 0 or 60 seconds
note, however, that each failed try is repeated _at once_, so that closed sockets and such things are catched immediately. 
moreover, _if_ the ui knows network becomes available again, the ui may bypass the calculated times by using dc_maybe_network(). on desktop, afaik, this function is currently never called, so that sending will be always delayed by these timespans.
=>  tweak get_backoff_time_offset()

src/dc_e2ee.c
delta chat uses [memoryhole](https://github.com/autocrypt/memoryhole) to protect and encrypt the subject of messages.
the protection of the subject is done by moving the subject header to the encypted part of the message; the original subject header can be used to add a "fallback" text that is displayed by MUAs before the message is really decrypted or by MUAs that do not support memoryhole at all.
most MUAs show sth. as "Encrypted Message" as the fallback text, which, however has some drawbacks and is annoying as the recent discussions on #autocrypt shows.
some drawbacks taken from there:
- using the word "encrypted" in the visible part may confuse users, esp. if they are using autocrypt and do not really care of encryption.  
"oh great, i have an encrypted messages" might be sth. a …
=> use '...' as the subject-fallback-text wrt memoryhole

src/dc_mimeparser.c
do not fallback to the subject for empty deltachat-messages (as the subject has no meaning for deltachat, this would result in empty messages displayed as the string `Chat:`)
closes #453
=> display empty messages as such

libs/netpgp/meson.build, meson.build, python/README.rst, python/wheelbuilder/Dockerfile, python/wheelbuilder/build-wheels.sh
Because I insist it's fine to install the dependencies manually, let's do that in a docker image and allow easy building of portable wheels.  Now people should be ok with getting python bindings.  We could even start distributing them on pypi if we wanted.
=> Let's build portable wheels

cmdline/cmdline.c, src/dc_chat.c, src/deltachat.h
this pr simplifies the api to get|set draft and also makes it more powerful, see #214 
a next pr will allow to save images, voice messages and other types as draft, currently, only text drafts can be handled (as before).
another api-change for these improvements is not needed, so that it makes sense to change the api already now so that android-dev and desktop need not to work with already deprecated functions.
=> change draft api

src/dc_chat.c
Noticed it ended up in the wrong place in the docs.
=> dc_get_draft() is a member of dc_context_t

src/dc_chat.c, src/dc_contact.c, src/dc_context.c, src/deltachat.h
- `dc_chat_get_profile_image()` returns the contact image for normal chats
- `dc_contact_get_profile_image()` added; currently the own profile image is returned for the SELF-chat (can be set using `dc_set_config(context, "selfavatar", image)`.
in the future, it is planned to return also the contact images received from remote users here, see #444
=> enhance profile-image api

src/dc_chat.c, src/dc_chat.h, src/dc_chatlist.c, src/dc_job.c, src/dc_lot.c, src/dc_msg.c, src/dc_msg.h, src/deltachat.h
in #457 we've changed the draft api so that it can set/get any `dc_msg_t` object as a draft - however, internally, still only text drafts were stored.
this pr changes the internal behavior so that the given `dc_msg_t` objects are really stored as drafts and can be restored later.
internal changes:
- draft are saved as messages in the normal `msgs` database
- the draft records are stored with the states `hidden=1` and `state=DC_STATE_OUT_DRAFT`
- each chat can have one draft (more are possible theoretically, however, currently a `dc_set_draft()` just overwrites the existing one for the given chat_id)
- loading the old draft texts/timestamps from the chats table removed
- reworking the sql commands
closes #214
=> improve draft handling

src/dc_chat.c, src/dc_contact.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h
this pr adds two functions that return "fine" colors for chats and contacts.
the colors can be used for drawing avatars or the names above messages in group chats.
=> get chat and contact colors

src/dc_tools.c
before going to the harder parts ;)
this pr changes the calculation contact/chat colors so that it becomes case-insensitive.
- on a multi-device-setup, this ensures, the fallback colors are the same for User@example.org and user@example.org
- as a side-effect, for chats, the color is not changed when just the case of the group name changes, which is also nice to have :)
=> ignore case when calculating colors

cmdline/main.c, src/dc_chat.h, src/dc_configure.c, src/dc_context.c, src/dc_context.h, src/dc_imap.c, src/dc_imap.h, src/dc_job.c, src/dc_job.h, src/deltachat.h
this pr is about to re-implement the move between the INBOX and the DeltaChat folder, see #422
we should also consider implementing #408 (check message-id before downloading) as moving between two watched folders results in threads waking up and some additional traffic.
=> [wip] move chat messages away

src/dc_context.c, src/dc_imap.c, src/dc_imap.h
this pr loads the Message-ID from the header already when getting the list of new messages.
if the Message-ID is known, it just updates the folder+uid in the database and skips downloading the whole message.
closes #408
=> check the Message-ID before downloading the complete message

deltachat-core.cbp, src/dc_configure.c, src/dc_context.c, src/dc_context.h, src/dc_imap.c, src/dc_imap.h, src/dc_job.c, src/dc_job.h, src/dc_move.c, src/dc_msg.c, src/dc_param.h, src/dc_receive_imf.c, src/meson.build
move messages as prototyped in https://github.com/deltachat/playground/blob/master/move_imap/move_imap.py#L150
tackles #422 (support DeltaChat folder) and #448 (mark self-bcc read), successor of #473
=> move messages from INBOX to MVBOX

src/dc_receive_imf.c
this pr is about to fix the group split that happens for various reasons, esp. in multi-device environments (originally, the whole group-id stuff was not developed with multi-device in mind and was more an ad-hoc approach to get things done)
- bb96a42 allows new members just use the new group-id and does not create a new group just because the `Chat-Group-Member-Added` message was missed. the identification of new group members is shifted from the `Chat-Group-Member-Added` header to the know message-id then.
i am pretty sure, there are more things to fix wrt group-splits, however, it is a start :)
=> fix group splits

src/dc_chat.c, src/dc_msg.c
this pr sets the mimetype for outgoing files if not yet done by [dc_msg_set_file()](https://c.delta.chat/classdc__msg__t.html#ae3d4b2a4ed4b10dbe13396ff7739160e).
this is useful if the ui does not set the mimetype but only the file.
Esp. for Voice-Messages in android-dev the mimetype was missing which is also corrected by this pr.
=> set mimetype for outgoing aac files

meson.build, src/meson.build
ToDo:
ToDo but not high priority as long as we depend on system installed libetpan:
=> Fix builds for mac

src/dc_array.c
Takes care of the following warnings:
```
../src/dc_array.c:254:58: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (array==NULL || array->magic!=DC_ARRAY_MAGIC || index<0 || index>=array->count) {
~~~~~^~
../src/dc_array.c:272:58: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (array==NULL || array->magic!=DC_ARRAY_MAGIC || index<0 || index>=array->count) {
~~~~~^~
../src/dc_array.c:290:58: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (array==NULL || array->magic!=DC_ARRAY_MAGIC || index<0 || index>=array->count) {
```
=> Remove index<0 comparison, always false for unsigned values

src/dc_aheader.h, src/dc_apeerstate.h, src/dc_contact.h, src/dc_context.h, src/dc_hash.h, src/dc_imap.h, src/dc_job.h, src/dc_jobthread.h, src/dc_key.h, src/dc_keyring.h, src/dc_loginparam.h, src/dc_mimefactory.h, src/dc_mimeparser.h, src/dc_msg.h, src/dc_param.h, src/dc_pgp.h, src/dc_saxparser.h, src/dc_simplify.h, src/dc_smtp.h, src/dc_sqlite3.h, src/dc_strbuilder.h, src/deltachat.h
this pr tries to avoid warnings that may be emmited wrt typedef's
see https://github.com/deltachat/deltachat-node/issues/223
i am not totally sure why the warning appears, however with https://github.com/deltachat/deltachat-core/pull/508/commits/eb25158ed7c6f9f046d0dd1d6e7a0dcdf00c58c1 i've separated strucuture definitions and typedefs (as already done for deltachat.h to allow opaque structures).
maybe this fixes the warning, or, at least make things a bit clearer.
Closes https://github.com/deltachat/deltachat-node/issues/223
=> avoid typedef warnings

src/dc_tools.c
Should fix the following warning:
```
../src/dc_tools.c:1392:6: warning: variable 'f' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
if ((pathNfilename_abs=dc_get_abs_path(context, pathNfilename))==NULL) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/dc_tools.c:1414:6: note: uninitialized use occurs here
if (f) {
^
../src/dc_tools.c:1392:2: note: remove the 'if' if its condition is always false
if ((pathNfilename_abs=dc_get_abs_path(context, pathNfilename))==NULL) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/dc_tools.c:1396:2: note: variable 'f' is declared here
FILE* f = fopen(pathNfilename_abs, "rb");
^
```
=> Initialize f to NULL to make sure it is initialized before cleanup

src/dc_chat.c
this pr stops marking messages as being forwarded if they are sent by the user himself.
this way, there is a simple "hack" to broadcast messages: 
- send a normal message to the first chat
- forward the message to all other chats that should also get the message
for the recipients, all messages appear in the same way and are not marked as "being forwarded".
(the "forward mark" is applied only to messages sent by other people then)
=> allow broadcasting own messages without marking them as being forwarded

src/dc_mimeparser.c, src/dc_receive_imf.c
do not show group-member-added-messages as images when they contain the group-profile-image.
fixes #506
=> do not show group-member-added-messages as images

src/dc_securejoin.c
this pr modifies the existing "join verified group" protocol so that it works also for normal groups.
the protocol is modified so that the `vg-member-added` message of step 6b may be sent unencrypted as in normal groups there may be members eg. without keys.
all other steps in the protocol are executed normally and the inviter is verified with the joiner afterwards.
steps:
closes #499
=> allow joining normal groups via qr-code

src/dc_lot.c
in general, we try to keep the summaries short; eg. we add the sender only in group threads and 'Me:' only in normal threads for messages that are not from the chat recipient.
for self-chats, however, the summary was _always_ prefixed by the string 'Me:' which is useless double information as the chat-name is already 'Me'.
this pr removes the prefix from these summaries.
nothing to be adapted in the ui.
=> do not add the prefix 'Me:' to summaries in the Me-chat

cmdline/cmdline.c, src/dc_chat.c, src/dc_job.c, src/dc_job.h, src/dc_msg.c, src/dc_sqlite3.c, src/dc_sqlite3.h
btw, all housekeeping is done the core, no need for the ui to do anything.
closes #484
=> housekeeping

src/dc_chat.c
=> do not display forwarded info-messages on the own device as info-messages

src/dc_contact.c
this pr makes dc_create_contact(<configured-address>) return DC_CONTACT_ID_SELF which is used to mark SELF in most lists.
closes https://github.com/deltachat/deltachat-android-ii/issues/238
=> dc_create_contact() and others take care about configured address

src/dc_imap.c
the problems was that `mailimap_fetch()` and `mailimap_uid_fetch()` may return a fetch_result != NULL on errors; this fetch_result. although set, is not valid then and must not be freed.
this pr checks if either an error is returned _or_  the fetch_result is NULL - in both cases, we set fetch_result to NULL so that it won't be freed again and regard the action as an error.
closes #527
=> fix crash in imap

src/dc_imap.c
this pr tries to fix some bugs related to the issue of downloading old messages, #156 ( o/ @adbenitez )
- https://github.com/deltachat/deltachat-core/commit/72df919fac4212476e8c2abd17ed5dbca8c11e54 fixes one - afterwards - obvious  bug that sets `lastseenuid` to a smaller value if `FETCH UID lastseenuid+1:*` returns values smaller than lastseenuid+1 - this should not happen, however it _does_. seen eg. on a stato server (cc @Ampli-fier :) 
- https://github.com/deltachat/deltachat-core/pull/533/commits/cd82fccf96f31c203a8d2e51ce4e8d96be536c9a initializes `lastseenuid` correctly if the folder is initially empty
i think, this could fix #156:
- `lastseenuid` can only grow, which is the most important fact. 
- might be that the initialization fails, however, reports i've heard from, …
=> [wip] avoid download old messages

src/dc_jobthread.c
when the folder configuration fails as eg. no SENT-folder could be figured out, the corresponding function returned state "disconnected", however, in fact, the connection was not disconnected.
this is fixed by this pr.
=> disconnect on failed folder configuration

meson.build
- Use build_machine as we don't support any form of cross-compilation
yet.
- Do not try to build the fallback etpan on osx.
Fixes #512
=> Small etpan/osx tweaks

cmdline/cmdline.c, src/dc_imex.c, src/dc_sqlite3.c, src/dc_sqlite3.h
while normally errors happening in sqlite are shown to the user, this pr stops doing so for the VACUUM command and writes the error only to the log.
the VACUUM command is called eg. after a successful export and the exported file is totally valid also without the VACUUM call. typical reasons fro the VACUUM command are "disk full" esp. on smaller android devices (VACUUM needs up to 3 times the size of the file so chances are good that this fails)
imho, we should not worry too much about this as there are already plans to do the whole export/import without VACUUM at all, #261
closes https://github.com/deltachat/deltachat-android/issues/418
=> tweak sqlite-errors

cmdline/main.c
this pr adds the parameter `--stress` the the cmdline-tool to allow only stresstesting the app.
=> add option to do stresstest only

meson.build
Now invoking `ninja test` will run the stress test built into the
command line tool.
=> Add support for the stress test in meson

src/dc_mimeparser.c, src/dc_mimeparser.h, src/dc_receive_imf.c
in verified groups, only encrypted messages encrypted and signed with out-of-band-verified keys are allowed. if a given message does not fulfill these needs, in the past, the message was shown in a parallel ad-hoc group. however, this results in some of ux problems, eg. missing overview, weired titles, and it was not clear what was going wrong.
if someone replies to the splitted group, things get even more worse :)
this pr tries to fix the problem by showing the reason of the problem in the original group; the original message text is only available dc_get_msg_info().
this way, replies go still to the same group and it is more clear who causes the problem and how it can be fixed.
closes #413
=> avoid group-splits on verification problems

python/tox.ini
Allows to test locally-built code without installing it in /usr/local first.
=> Tell tox to pass LD_LIBRARY_PATH for testing of local code during development

src/dc_context.c, src/dc_mimefactory.c
just a minor change to make things about the X-Mailer header clearer:
- the header always starts with `Delta Chat Core` followed by the version of the core
- optionally, after a slash, system specific name and/or version are added as given to [dc_context_new()](https://c.delta.chat/classdc__context__t.html#a9d0f77a01382745e59492dda8509cf83)
this may result in sth. as `X-Mailer: Delta Chat Core 0.40.0/DC Windows 0.101.0` where the string after the slash is completely configurable while guaranteeing a unique string beginning which may be handy for filtering here and there.
closes https://github.com/deltachat/deltachat-desktop/issues/679
closes https://github.com/deltachat/deltachat-android/issues/730
=> be more specific about version in X-Mailer header, allow more general suffix

src/dc_move.c, src/dc_msg.h, src/dc_receive_imf.c
leaving delta chat messages in the inbox to keep threads together seems to scare users more that tearing threads.
this pr moves messages with a `Chat-Version:` header to the DeltaChat folder. moreover, replies to dc messages are moved and the current move_state is tracked so that we can go for more complicated heuristics optionally at a later time.
this should result in a cleaner inbox and we can iterate from there, maybe add an option later or so.
this also mitigates the bcc-self story as these messages should also be moved in all cases and no more self-sent messages stay in the inbox.
this pr partly reverts https://github.com/deltachat/deltachat-core/commit/51bcf16c8c7d961d17eed723369b8a2e009fb784#diff-1d2adc03d043975786fd5caef8655673 and surrounding commits.
=> simplify moving of dc messages

src/dc_apeerstate.c, src/dc_apeerstate.h, src/dc_chat.c, src/dc_chat.h, src/dc_context.h, src/dc_e2ee.c, src/dc_job.c, src/dc_mimefactory.c, src/dc_mimefactory.h, src/dc_receive_imf.c, src/dc_sqlite3.c
the aim of this pr is to add the [Autocrypt-Gossip](https://autocrypt.org/level1.html#key-gossip) headers less often without limiting its functionality too much.
for this purpose, the following changes are done:
- each chat has a timestamp marking the time of the last outgoing gossiped keys (`gossiped_timestamp`)
- `gossiped_timestamp` defaults to `0`
- `gossiped_timestamp` is reset (set to  `0`) for a single chat whenever the memberlist of the chat changes (never for 1:1 chats)
- `gossiped_timestamp` is reset for all chats on any incoming key changes (if needed, this can be optimized to reset `gossiped_timestamp` only for chats that really use the changed keys)
- finally, outgoing keys are gossiped only when `gossiped_timestamp` for a chat is `0` or older than 48 hours.
this saves about …
=> tone down gossip

src/dc_configure.c
seems to be far away from standard but also is known to be used eg. in cuba.
as this probe is done if everything else is failing and does not force a PLAIN connection, however, i think it should not harm (famous last words (tm))
=> probing STARTTLS on port 25

src/dc_chat.c, src/dc_context.c, src/dc_context.h, src/dc_receive_imf.c, src/dc_sqlite3.c, src/dc_stock.c, src/deltachat.h
this pr will improve the interaction between chats and email and is the core-part of https://github.com/deltachat/deltachat-android/pull/742
todo:
in the future, when things work out, we can refine the downloading of messages then - eg. maybe avoiding to download non-chat-mails at all.
=> email interactions

src/dc_mimeparser.c, src/dc_move.c
with https://github.com/deltachat/deltachat-core/pull/588 (email-interations), emails are not shown by default.
however, autocrypt-setup-messages should always show up.
this pr fixes this issue.
(there was no official release where the asm did not work)
=> show up autocrypt setup messages even if emails are not displayed

src/dc_pgp.h
this pr changes the default key size to 2048 bit
the previously used 3072 bit only [add only few entropy](https://www.gnupg.org/faq/gnupg-faq.html#no_default_of_rsa4096) (128 bit vs. 112 bit) and have huge drawbacks as slow generation, operations and larger sizes. also the 112 bit fit good to the entropy used for the [setup code](https://autocrypt.org/level1.html#setup-code) 
the mid-term plan, however is to go for ecc keys.
users can still import keys of other sizes as they like.
=> adapt key size

src/dc_job.c, src/dc_msg.c, src/dc_msg.h, src/dc_sqlite3.c
this pr does not sent generated mime-structure out if the corresponding database entry does not or no longer exist on sending time. 
this is typically the case if one sends a message without having network and deletes the message before the network comes back again.
due to the early-mime-generation, we _could_ send out the message in this case, however, usually, this is not desired.
finally, this pr also adds the [AUTOINCREMENT](https://sqlite.org/autoinc.html) keyword, to avoid problems eg. if the last message was delete before sending but _another_ messages get the same msg_id later on. as this flag is not easily changeable for existing databases, we add it only for new ones. in practice, however, messages are not directly deleted but marked with a special flag and are physically delete …
=> handle delete wrt early-mime-generation

python/tests/test_increation.py, src/dc_chat.c
To allow UIs to rely entirely on events do display messages, `dc_prepare_msg()` should emit events just like `dc_send_msg()`. Calling `dc_send_msg()` directly will emit the event only once, since the PREPARING state is skipped entirely.
=> Emit DC_EVENT_MSGS_CHANGED from dc_prepare_msg()

cmdline/cmdline.c, cmdline/main.c, cmdline/stress.c, src/dc_array.c, src/dc_array.h, src/dc_context.h, src/dc_job.c, src/dc_job.h, src/dc_location.c, src/dc_mimefactory.c, src/dc_mimefactory.h, src/dc_mimeparser.c, src/dc_mimeparser.h, src/dc_receive_imf.c, src/dc_sqlite3.c, src/dc_stock.c, src/dc_tools.c, src/dc_tools.h, src/deltachat.h, src/meson.build
this pr aims to provide basic functions to allow the streaming of locations.
=> location streaming

python/src/deltachat/account.py, python/tests/conftest.py, python/tests/test_account.py
also print out core, rpgp, sqlite, openssl versions in the header of the test.
=> add account.get_info()

src/dc_sqlite3.c
to avoid errors in databases with only partly created location-tables, check for null pointers
=> bump db version

cmdline/stress.c, src/dc_context.c
this should make atof() and printf("%f") work as expected, needed eg. to parse latitude and longitude from kml files
=> call setlocale() to force point as decimal separator for floats

src/dc_tools.c
this pr doubles the number of available colors for contacs and groups (if no image is set) and decreases the probability of a collisions (as the color is never the only hint, collisions as such are okay).
the colors must fulfill some criterions as: contrast to black and to white, work as a text-color, being noticable on a map and harmonize together while being differnt enough - therefore, we cannot just use random rgb colors :)
new palette:
=> add some more colors

cmdline/cmdline.c, src/dc_array.c, src/dc_context.h, src/dc_location.c, src/deltachat.h
this pr modified dc_get_location() so that `0` can be given as a contact id. together with the timespan and the chat_id, this function some powerful filtering options that can be used for both, global and chat map.
=> more powerful dc_get_locations()

cmdline/cmdline.c, src/dc_location.c
this pr modifies dc_is_sending_locations_to_chat() so that it can be used to check if location-streaming is enabled for _any_ chat.
this is useful esp. on program startup where the app may want to initialize the location-engine only if needed.
=> quick-check if location-streaming is enabled for any chat

src/dc_context.c, src/dc_receive_imf.c
they were not really notified as the state is checked again later, however, hidden messages should not even being returned from dc_get_fresh_msgs()
=> do not notify hidden location messages

src/dc_sqlite3.c
this pr modifies the id-column in the jobs table so that no id is used twice. 
the standard sqlite behavior is to reuse ids. so it might happen that a newly added job gets the same id as a job that was executed and already removed from the database.
this may be a problem if we decide to use the job-ids from external, eg. to check if a given job was executed.
tackles the raw-receiving of mime-messages.
=> autoincrement id in jobs-table

python/tox.ini
This should hopefully fix the CI again.  The version pinning might
be overly strict, not sure how versions work in tox though.
=> Use newer sphinx

python/src/deltachat/account.py
In the current version this was a tuple containing two elements. Now it is just a string wrapped in parentheses => simplify to check by direct comparison.
=> Make intention clear, rather than work by accident

README.md
This is needed for the node bindings on linux in case libetpan is too old. Since we're referring to this repository from the node bindings I thought it was best to put the information in this readme.
=> Document compiling/installing libetpan

meson.build
The current way of using some git magic to determine the dcc version fails because it's not run in the correct folder. This blocks us from using the current core in -desktop. As meson will go away soon anyway, i just hardcoded the current version. Hotfix.
=> Hardcode version in meson.build

cmdline/cmdline.c, src/dc_context.c, src/dc_imap.c, src/dc_imap.h, src/dc_job.c, src/dc_job.h, src/deltachat.h
this pr adds a function to empty the mvbox and inbox. 
note that this is subject to changes, there is no need to port this directly to rust. the mid-goal is to have an automatic deletion that cleans up the folder every few days so that multi-device-support is possible and no user-action is required for deletion.
=> empty server folder
